version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.3
    - 12.0.4
  - dependency-name: electron-builder
    versions:
    - 22.10.5
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: music-metadata
    versions:
    - 7.7.0
    - 7.8.1
    - 7.8.3
    - 7.8.4
  - dependency-name: electron-store
    versions:
    - 7.0.3
  - dependency-name: electron-updater
    versions:
    - 4.3.8
